### ISSUE TITLE
Build has been failing; do not know where the issue lies

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Center-on-Regional-Politics#10]
Hey WC can you take a look at the html proffer and this error message? Screenshot below, this has been failing for a couple of weeks and want to get it going green again! Thanks! 

![corp build fail](https://user-images.githubusercontent.com/15130721/71843150-35400280-3091-11ea-967f-572a0a35e1b8.png)

**Comment by tu-chill** [comment]
External links seem to be failing link checker. Something wrong is happening on the server-side for these linked pages.  malformed headers? the only solution right now would be to remove the link.
