### ISSUE TITLE
Image alignment on Publications page

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Center-on-Regional-Politics#2]
Hey WC can you help me align the images and links to these publications on the Publications page?
http://develop.cla.temple.edu/institute-for-public-policy/publications/ They are all haywire, the images are the right sizes...

**Comment by tu-chill** [comment]
Hi, @CVE82 we just talked. You were gonna do the thing we did with classics. Ask Sam if you need help.

**Comment by CVE82** [comment]
@tu-chill Roger that grey squirrel!
