### ISSUE TITLE
Hero Question

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Center-on-Regional-Politics#5]
Hey Zac, is there any way possible to make their current hero work, it's perfect to describe the center...

https://github.com/TULiberalArts/Center-on-Regional-Politics/blob/master/media/center-on-regional-politics.png

**Comment by ZMcGroarty** [comment]
Lets see how this squares up
![corp](https://user-images.githubusercontent.com/15017242/47662125-bee07000-db70-11e8-97d3-cc0aa916f298.png)

**Comment by CVE82** [comment]
This is perfect, thanks so much!!
