### ISSUE TITLE
Media mentions entered in drupal not pulling through to CORP site

### ISSUE THREAD

**Issue by tu-chill** [TULiberalArts/Center-on-Regional-Politics#8]
There are a few reasons this might not be happening. 
1. we never set it up
2. we set it up and we just need to force a build on the repo
3. we set it up but the node in Drupal was not "tagged" with the center. so the filter on the view is empty.
4. There is no view for this center. no view no data file no import no update.

There may be other reasons but in the past, this short list usually uncovers what we need

**Comment by CVE82** [comment]
I didn't know there was a media mention waiting to go since last week, I will make the view.

**Comment by CVE82** [comment]
Checked all of these and everything is correct. Do not know where to look next, the media mentions are pulling through on the view in the csv, csv is attached. 
[center_on_regional_politics_media_mentions.xlsx](https://github.com/TULiberalArts/Center-on-Regional-Politics/files/2761370/center_on_regional_politics_media_mentions.xlsx)
